[package]
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
build = "build.rs"
name = "static-analyser"
version = "0.1.0"

[build-dependencies]
tango = "0.7"

[dependencies]
error-chain = "0.11"
pretty_assertions = "0.3.4"
